add qng utxo explorer frame
Qitmeer/meerscout pull request #3
Opened 2024-12-15 16:34 UTC by frankcrypto2023

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-12-23 05:50 UTC, dindinw requested changes
Please fix GitHub Actions warning about `Unknown word (UTXO)`

2024-12-23 05:50 UTC, dindinw commented on apps/explorer/priv/repo/migrations/20241219221922_create_utxoblocks.exs
> +defmodule Explorer.Repo.Migrations.CreateUTXOBlocks do
should `priv/repo/xxx` excluded from the source control ? Is it some kind of intermediate product?

2024-12-23 05:53 UTC, dindinw commented
Please Clean the PR's description information

2025-01-02 09:28 UTC, dindinw commented on apps/explorer/lib/explorer/counters/addresses_counter.ex
> +            IO.puts("Key #{cache_key} not found in ETD table.")
cache_key()

2025-01-02 09:35 UTC, dindinw commented on CHANGELOG.md
> +- [#7832](https://github.com/blockscout/blockscout/pull/7832), [#7891](https://github.com/blockscout/blockscout/pull/7891) - API v2: Add block_number, blockhash to logs
Why the file changed?

2025-01-02 09:39 UTC, dindinw commented on apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex
> -  @enabled Keyword.get(config, :enabled)
why change this?

2025-01-02 09:42 UTC, dindinw commented on config/config_helper.exs
> -
why change the file?

2025-01-02 09:43 UTC, dindinw commented on cspell.json
>  // cSpell Settings
why change the file?

2025-01-03 16:29 UTC, closed without merging

2025-01-03 16:37 UTC, frankcrypto2023 commented
pr #5